export default {
    Snatcher: [1, 1, 1, 1, 1],
    Map: 4,
    Waves: [2, 3, 1, 15, 0],
    Weapons: ["Shooter_QuickMiddle", "Roller_Compact", "Shooter_Flash", "Shelter_Wide"],
    Specials: ["SpCastle", "SpJetpack", "SpTripleTornado", "SpMicroLaser"],
    Spawns: {
        1: {
            300: [
                {
                    Spawn: "B",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 0,
                    SubSpawn: 2,
                },
                {
                    Spawn: "A",
                    Timing: 1080,
                    Lesser: true,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "A",
                    Timing: 1080,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "Sakerocket",
                    Spawn: "B",
                    Timing: 2160,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakerocket",
                    Spawn: "B",
                    Timing: 2328,
                    SubSpawn: 1,
                },
                {
                    Spawn: "A",
                    Timing: 3240,
                    Lesser: true,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "A",
                    Timing: 3240,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakerocket",
                    Spawn: "A",
                    Timing: 4066,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "C",
                    Timing: 4320,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 5400,
                    Lesser: true,
                },
            ],
        },
        2: {
            300: [
                {
                    Targets: [2, 0, 3, 0, 2, 3, 1, 2, 0, 1],
                },
                {
                    Spawn: "B",
                    Timing: 0,
                },
                {
                    Spawn: "A",
                    Timing: 1080,
                },
                {
                    Spawn: "B",
                    Timing: 2160,
                },
                {
                    Spawn: "C",
                    Timing: 3240,
                },
                {
                    Spawn: "B",
                    Timing: 4320,
                },
                {
                    Spawn: "A",
                    Timing: 5400,
                },
            ],
            450: [
                {
                    Targets: [2, 0, 3, 0, 2, 3, 1, 2, 0, 1],
                },
                {
                    Spawn: "B",
                    Timing: 0,
                },
                {
                    Spawn: "A",
                    Timing: 1080,
                },
                {
                    Spawn: "B",
                    Timing: 2160,
                },
                {
                    Spawn: "C",
                    Timing: 3240,
                },
                {
                    Spawn: "B",
                    Timing: 4320,
                },
                {
                    Spawn: "A",
                    Timing: 5400,
                },
            ],
            600: [
                {
                    Targets: [2, 0, 3, 0, 2, 3, 1, 2, 0, 1],
                },
                {
                    Spawn: "B",
                    Timing: 0,
                },
                {
                    Spawn: "A",
                    Timing: 864,
                },
                {
                    Spawn: "B",
                    Timing: 1728,
                },
                {
                    Spawn: "C",
                    Timing: 2592,
                },
                {
                    Spawn: "B",
                    Timing: 3456,
                },
                {
                    Spawn: "A",
                    Timing: 4320,
                },
                {
                    Spawn: "B",
                    Timing: 5184,
                },
            ],
        },
        3: {
            300: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakerocket",
                    Spawn: "C",
                    Timing: 985,
                    SubSpawn: 2,
                },
                {
                    Spawn: "B",
                    Timing: 1080,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 1080,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "B",
                    Timing: 1209,
                    SubSpawn: 2,
                },
                {
                    Spawn: "C",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 2160,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 3057,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "C",
                    Timing: 3076,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 3240,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 3240,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 3254,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 3631,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "A",
                    Timing: 4320,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 5400,
                    Lesser: true,
                },
            ],
            450: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakerocket",
                    Spawn: "C",
                    Timing: 31,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 985,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 1080,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "A",
                    Timing: 1080,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "A",
                    Timing: 1209,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "A",
                    Timing: 1982,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 2160,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 3057,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 3076,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 3240,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 3240,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 3254,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "B",
                    Timing: 3631,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 4003,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 4320,
                    SubSpawn: 1,
                },
                {
                    Spawn: "A",
                    Timing: 5400,
                    Lesser: true,
                },
            ],
            600: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakerocket",
                    Spawn: "C",
                    Timing: 313,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 358,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 864,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "A",
                    Timing: 864,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "A",
                    Timing: 1475,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "A",
                    Timing: 1652,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 1728,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 1728,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 1753,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 1831,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 2592,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 2592,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 3314,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "B",
                    Timing: 3324,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 3456,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "A",
                    Timing: 3456,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "A",
                    Timing: 3467,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "A",
                    Timing: 4173,
                    SubSpawn: 1,
                },
                {
                    Spawn: "C",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 4320,
                    SubSpawn: 2,
                },
                {
                    Spawn: "A",
                    Timing: 5184,
                    Lesser: true,
                },
            ],
            750: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakerocket",
                    Spawn: "C",
                    Timing: 62,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 598,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 720,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "A",
                    Timing: 720,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "A",
                    Timing: 980,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "A",
                    Timing: 1078,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 1440,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 1440,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 1738,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 2097,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 2160,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 2246,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "B",
                    Timing: 2669,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 2880,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "A",
                    Timing: 2880,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "A",
                    Timing: 2901,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "A",
                    Timing: 3490,
                    SubSpawn: 1,
                },
                {
                    Spawn: "C",
                    Timing: 3600,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 3600,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 3609,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 4201,
                    SubSpawn: 2,
                },
                {
                    Spawn: "A",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "A",
                    Timing: 4320,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 5040,
                    Lesser: true,
                },
                {
                    Spawn: "C",
                    Timing: 5760,
                    Lesser: true,
                },
            ],
            900: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakerocket",
                    Spawn: "C",
                    Timing: 62,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 598,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 720,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "A",
                    Timing: 720,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "A",
                    Timing: 980,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "A",
                    Timing: 1078,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 1440,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 1440,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 1738,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 2097,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 2160,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 2246,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "B",
                    Timing: 2624,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 2669,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 2880,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 2880,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 2901,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "C",
                    Timing: 3157,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 3490,
                    SubSpawn: 2,
                },
                {
                    Spawn: "A",
                    Timing: 3600,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "A",
                    Timing: 3600,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "A",
                    Timing: 3609,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "A",
                    Timing: 4201,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "A",
                    Timing: 4280,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "B",
                    Timing: 4320,
                    SubSpawn: 2,
                },
                {
                    Spawn: "C",
                    Timing: 5040,
                    Lesser: true,
                },
                {
                    Spawn: "A",
                    Timing: 5760,
                    Lesser: true,
                },
            ],
        },
        4: {
            300: [
                {
                    Targets: [36, 16, 23, 20, 11],
                },
            ],
            450: [
                {
                    Targets: [36, 16, 23, 20, 11],
                },
            ],
            600: [
                {
                    Targets: [36, 16, 23, 20, 11],
                },
            ],
            750: [
                {
                    Targets: [36, 16, 23, 20, 11],
                },
            ],
            900: [
                {
                    Targets: [36, 16, 23, 20, 11],
                },
            ],
            1050: [
                {
                    Targets: [36, 16, 23, 20, 11],
                },
            ],
            1200: [
                {
                    Targets: [36, 16, 23, 20, 11],
                },
            ],
        },
        5: {
            300: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 623,
                    SubSpawn: 3,
                },
                {
                    Spawn: "B",
                    Timing: 1080,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 1080,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 2046,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "Sakerocket",
                    Spawn: "A",
                    Timing: 2160,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "A",
                    Timing: 2207,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "A",
                    Timing: 2423,
                    SubSpawn: 4,
                },
                {
                    Spawn: "B",
                    Timing: 3240,
                    Lesser: true,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 3240,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "B",
                    Timing: 3609,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 4052,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 4320,
                    SubSpawn: 3,
                },
                {
                    Spawn: "A",
                    Timing: 5400,
                    Lesser: true,
                },
            ],
            450: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 623,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 1069,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 1080,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "B",
                    Timing: 1080,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 1964,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 2046,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "C",
                    Timing: 2160,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 2207,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 2423,
                    SubSpawn: 2,
                },
                {
                    Spawn: "B",
                    Timing: 3240,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "B",
                    Timing: 3240,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 3337,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 3609,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 4052,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 4320,
                    SubSpawn: 3,
                },
                {
                    Spawn: "A",
                    Timing: 5400,
                    Lesser: true,
                },
            ],
            600: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 137,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 295,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 864,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "B",
                    Timing: 864,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 941,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 1362,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 1728,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "C",
                    Timing: 1728,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 2501,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 2583,
                    SubSpawn: 2,
                },
                {
                    Spawn: "B",
                    Timing: 2592,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "B",
                    Timing: 2592,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 2629,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 3299,
                    SubSpawn: 1,
                },
                {
                    Spawn: "C",
                    Timing: 3456,
                    Lesser: true,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "C",
                    Timing: 3456,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "C",
                    Timing: 3666,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 4106,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 4320,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 5184,
                    Lesser: true,
                },
            ],
            750: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 175,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 341,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 720,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "B",
                    Timing: 720,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 922,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 966,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 1440,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "C",
                    Timing: 1440,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 1554,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 1855,
                    SubSpawn: 2,
                },
                {
                    Spawn: "B",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "B",
                    Timing: 2160,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 2224,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 2804,
                    SubSpawn: 1,
                },
                {
                    Spawn: "C",
                    Timing: 2880,
                    Lesser: true,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "C",
                    Timing: 2880,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "C",
                    Timing: 2911,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 3592,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 3600,
                    Lesser: true,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 3600,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 4141,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 4189,
                    SubSpawn: 1,
                },
                {
                    Spawn: "C",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "C",
                    Timing: 4320,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 5040,
                    Lesser: true,
                },
                {
                    Spawn: "B",
                    Timing: 5760,
                    Lesser: true,
                },
            ],
            900: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 175,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 341,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 720,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "B",
                    Timing: 720,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 922,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 966,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 1440,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "C",
                    Timing: 1440,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 1554,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 1855,
                    SubSpawn: 2,
                },
                {
                    Spawn: "B",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "B",
                    Timing: 2160,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 2224,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 2350,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 2804,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 2880,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 2880,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "C",
                    Timing: 2911,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 2975,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "C",
                    Timing: 3592,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 3600,
                    Lesser: true,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 3600,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "B",
                    Timing: 3922,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 4141,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 4189,
                    SubSpawn: 2,
                },
                {
                    Spawn: "C",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "C",
                    Timing: 4320,
                    SubSpawn: 2,
                },
                {
                    Spawn: "B",
                    Timing: 5040,
                    Lesser: true,
                },
                {
                    Spawn: "C",
                    Timing: 5760,
                    Lesser: true,
                },
            ],
            1050: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 81,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 505,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 617,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "B",
                    Timing: 617,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 767,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 893,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 1234,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "C",
                    Timing: 1234,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 1445,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 1526,
                    SubSpawn: 2,
                },
                {
                    Spawn: "B",
                    Timing: 1851,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "B",
                    Timing: 1851,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 2024,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 2207,
                    SubSpawn: 1,
                },
                {
                    Spawn: "C",
                    Timing: 2468,
                    Lesser: true,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "C",
                    Timing: 2468,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "C",
                    Timing: 2566,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 3020,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 3085,
                    Lesser: true,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 3085,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 3111,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 3140,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "B",
                    Timing: 3253,
                    SubSpawn: 2,
                },
                {
                    Spawn: "A",
                    Timing: 3702,
                    Lesser: true,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "A",
                    Timing: 3702,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "A",
                    Timing: 3865,
                    SubSpawn: 4,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "A",
                    Timing: 4166,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "A",
                    Timing: 4312,
                    SubSpawn: 2,
                },
                {
                    Spawn: "B",
                    Timing: 4319,
                    Lesser: true,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 4319,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 4937,
                    Lesser: true,
                },
                {
                    Spawn: "B",
                    Timing: 5554,
                    Lesser: true,
                },
            ],
            1200: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 81,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 505,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 617,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "B",
                    Timing: 617,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 767,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 893,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 1234,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "C",
                    Timing: 1234,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 1400,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 1445,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "C",
                    Timing: 1526,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 1851,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "B",
                    Timing: 1851,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 2024,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 2207,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 2455,
                    SubSpawn: 1,
                },
                {
                    Spawn: "C",
                    Timing: 2468,
                    Lesser: true,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "C",
                    Timing: 2468,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 2566,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "C",
                    Timing: 3009,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "C",
                    Timing: 3020,
                    SubSpawn: 1,
                },
                {
                    Spawn: "B",
                    Timing: 3085,
                    Lesser: true,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 3085,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 3111,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 3140,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 3253,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 3702,
                    Lesser: true,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 3702,
                    SubSpawn: 3,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 3865,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "C",
                    Timing: 4166,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "C",
                    Timing: 4312,
                    SubSpawn: 2,
                },
                {
                    Spawn: "A",
                    Timing: 4319,
                    Lesser: true,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "A",
                    Timing: 4319,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 4937,
                    Lesser: true,
                },
                {
                    Spawn: "C",
                    Timing: 5554,
                    Lesser: true,
                },
            ],
            1350: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 147,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 534,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 540,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "B",
                    Timing: 540,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 683,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 982,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 1080,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "C",
                    Timing: 1080,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 1151,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 1211,
                    SubSpawn: 2,
                },
                {
                    Spawn: "B",
                    Timing: 1620,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "B",
                    Timing: 1620,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 1804,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 1861,
                    SubSpawn: 1,
                },
                {
                    Spawn: "C",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "C",
                    Timing: 2160,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "C",
                    Timing: 2332,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 2416,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 2471,
                    SubSpawn: 2,
                },
                {
                    Spawn: "B",
                    Timing: 2700,
                    Lesser: true,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 2700,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 2845,
                    SubSpawn: 0,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "B",
                    Timing: 2851,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 3183,
                    SubSpawn: 1,
                },
                {
                    Spawn: "C",
                    Timing: 3240,
                    Lesser: true,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "C",
                    Timing: 3240,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "C",
                    Timing: 3263,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 3326,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 3769,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 3780,
                    Lesser: true,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "A",
                    Timing: 3780,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "A",
                    Timing: 3828,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "A",
                    Timing: 4186,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "A",
                    Timing: 4254,
                    SubSpawn: 5,
                },
                {
                    Spawn: "B",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 4320,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 4860,
                    Lesser: true,
                },
                {
                    Spawn: "A",
                    Timing: 5400,
                    Lesser: true,
                },
                {
                    Spawn: "B",
                    Timing: 5940,
                    Lesser: true,
                },
            ],
            1500: [
                {
                    Spawn: "C",
                    Timing: 0,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 0,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 147,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 534,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 540,
                    Lesser: true,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "B",
                    Timing: 540,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "B",
                    Timing: 683,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 956,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "B",
                    Timing: 982,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 1080,
                    Lesser: true,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "C",
                    Timing: 1080,
                    SubSpawn: 1,
                },
                {
                    Boss: "Sakerocket",
                    Spawn: "C",
                    Timing: 1151,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "C",
                    Timing: 1211,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "C",
                    Timing: 1552,
                    SubSpawn: 0,
                },
                {
                    Spawn: "A",
                    Timing: 1620,
                    Lesser: true,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "A",
                    Timing: 1620,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "A",
                    Timing: 1804,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "A",
                    Timing: 1809,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "A",
                    Timing: 1861,
                    SubSpawn: 2,
                },
                {
                    Spawn: "C",
                    Timing: 2160,
                    Lesser: true,
                },
                {
                    Boss: "SakePillar",
                    Spawn: "C",
                    Timing: 2160,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "C",
                    Timing: 2332,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "C",
                    Timing: 2416,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 2471,
                    SubSpawn: 2,
                },
                {
                    Spawn: "A",
                    Timing: 2700,
                    Lesser: true,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "A",
                    Timing: 2700,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "A",
                    Timing: 2845,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "A",
                    Timing: 2851,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "A",
                    Timing: 3183,
                    SubSpawn: 0,
                },
                {
                    Spawn: "B",
                    Timing: 3240,
                    Lesser: true,
                },
                {
                    Boss: "SakeSaucer",
                    Spawn: "B",
                    Timing: 3240,
                    SubSpawn: 3,
                },
                {
                    Boss: "SakelienSnake",
                    Spawn: "B",
                    Timing: 3263,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienShield",
                    Spawn: "B",
                    Timing: 3326,
                    SubSpawn: 2,
                },
                {
                    Boss: "SakelienCupTwins",
                    Spawn: "B",
                    Timing: 3769,
                    SubSpawn: 0,
                },
                {
                    Spawn: "C",
                    Timing: 3780,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "C",
                    Timing: 3780,
                    SubSpawn: 3,
                },
                {
                    Boss: "Sakediver",
                    Spawn: "C",
                    Timing: 3828,
                    SubSpawn: 1,
                },
                {
                    Boss: "SakelienTower",
                    Spawn: "C",
                    Timing: 4186,
                    SubSpawn: 0,
                },
                {
                    Boss: "SakeDolphin",
                    Spawn: "C",
                    Timing: 4254,
                    SubSpawn: 1,
                },
                {
                    Spawn: "B",
                    Timing: 4320,
                    Lesser: true,
                },
                {
                    Boss: "SakelienBomber",
                    Spawn: "B",
                    Timing: 4320,
                    SubSpawn: 3,
                },
                {
                    Spawn: "C",
                    Timing: 4860,
                    Lesser: true,
                },
                {
                    Spawn: "B",
                    Timing: 5400,
                    Lesser: true,
                },
                {
                    Spawn: "C",
                    Timing: 5940,
                    Lesser: true,
                },
            ],
        },
    },
}
